// NotificationLogPage.jsx — FSD 5.7 "Notification and Audit Details" screen.
// Read-only by nature (every row is system-generated by /auditflow's Insert
// row step, not user-authored), so it follows the app's standard KPI-cards
// -> searchable-grid -> slide-over pattern but with a "View Details" panel
// instead of an Add/Edit form — there's nothing here for a user to create
// or edit. Wired to the existing "mail-notification" module (see
// constants/modules.js) rather than a new module key, since that
// permission row already existed as an unused stub.
import { useState, useEffect, useCallback } from "react";
import {
  Search, RefreshCw, Bell, Filter, ArrowUpDown, AlertCircle, Loader2,
  CheckCircle2, XCircle, SkipForward, X, Mail,
} from "lucide-react";
import { callNotificationLogFlow } from "../../api/flows";
import { EmptyState } from "../../components/common/EmptyState";
import { COLORS, cardStyle, inputStyle } from "../../constants/theme";

const STATUS_META = {
  Sent: { color: COLORS.success, bg: COLORS.successSoft, icon: CheckCircle2 },
  Failed: { color: COLORS.danger, bg: COLORS.dangerSoft, icon: XCircle },
  Skipped: { color: COLORS.warning, bg: COLORS.warningSoft, icon: SkipForward },
};
const statusMeta = (s) => STATUS_META[s] || { color: COLORS.textMuted, bg: COLORS.bg, icon: Mail };

function StatCard({ label, value, icon: Icon, color, sub }) {
  return (
    <div style={{ ...cardStyle, flex: 1, minWidth: 160, display: "flex", flexDirection: "column", gap: 6 }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <span style={{ fontSize: 12.5, color: COLORS.textMuted, fontWeight: 600 }}>{label}</span>
        <div style={{ width: 30, height: 30, borderRadius: 9, background: `${color}1A`, display: "flex", alignItems: "center", justifyContent: "center" }}>
          <Icon size={15} color={color} />
        </div>
      </div>
      <div style={{ fontFamily: "Sora, sans-serif", fontSize: 22, fontWeight: 700, color: COLORS.text }}>{value}</div>
      {sub && <span style={{ fontSize: 12, color: COLORS.textMuted }}>{sub}</span>}
    </div>
  );
}

export function NotificationLogPage() {
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [listError, setListError] = useState("");
  const [search, setSearch] = useState("");
  const [eventFilter, setEventFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [sortDir, setSortDir] = useState("desc");
  const [detail, setDetail] = useState(null);

  const refresh = useCallback(() => {
    setLoading(true);
    setListError("");
    callNotificationLogFlow("LIST")
      .then((res) => { setRows(res.data); setLoading(false); })
      .catch((e) => { setListError(e.message); setLoading(false); });
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  const eventOptions = Array.from(new Set(rows.map((r) => r.emailType))).filter(Boolean).sort();

  const isToday = (d) => d && new Date(d).toDateString() === new Date().toDateString();
  const sentCount = rows.filter((r) => r.deliveryStatus === "Sent").length;
  const failedCount = rows.filter((r) => r.deliveryStatus === "Failed").length;
  const skippedCount = rows.filter((r) => r.deliveryStatus === "Skipped").length;
  const todayCount = rows.filter((r) => isToday(r.sentDate)).length;

  const filtered = rows
    .filter((r) => {
      const q = search.toLowerCase();
      const matchesSearch = !q
        || (r.recipientEmail || "").toLowerCase().includes(q)
        || (r.subjectLine || "").toLowerCase().includes(q)
        || (r.emailType || "").toLowerCase().includes(q);
      const matchesEvent = !eventFilter || r.emailType === eventFilter;
      const matchesStatus = !statusFilter || r.deliveryStatus === statusFilter;
      const t = new Date(r.sentDate).getTime();
      const matchesFrom = !dateFrom || t >= new Date(dateFrom).getTime();
      const matchesTo = !dateTo || t <= new Date(dateTo).getTime() + 86399999;
      return matchesSearch && matchesEvent && matchesStatus && matchesFrom && matchesTo;
    })
    .sort((a, b) => {
      const diff = new Date(a.sentDate) - new Date(b.sentDate);
      return sortDir === "desc" ? -diff : diff;
    });

  return (
    <div style={{ flex: 1, display: "flex", overflow: "hidden", position: "relative" }}>
      <div style={{ flex: 1, padding: 26, overflowY: "auto" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 18, flexWrap: "wrap", gap: 12 }}>
          <div>
            <div style={{ fontFamily: "Sora, sans-serif", fontSize: 20, fontWeight: 700, color: COLORS.text }}>Notification Log</div>
            <div style={{ color: COLORS.textMuted, fontSize: 13.5 }}>Every business-event mail the app has sent, skipped, or failed to send</div>
          </div>
          <button onClick={refresh} style={{ display: "flex", alignItems: "center", gap: 6, border: `1px solid ${COLORS.border}`, background: "#fff", borderRadius: 8, padding: "8px 14px", fontSize: 12.5, cursor: "pointer", color: COLORS.text }}>
            <RefreshCw size={13} /> Refresh
          </button>
        </div>

        <div style={{ display: "flex", gap: 14, flexWrap: "wrap", marginBottom: 18 }}>
          <StatCard label="Total Notifications" value={rows.length} icon={Bell} color={COLORS.accent} />
          <StatCard label="Sent" value={sentCount} icon={CheckCircle2} color={COLORS.success} />
          <StatCard label="Failed" value={failedCount} icon={XCircle} color={COLORS.danger} />
          <StatCard label="Skipped" value={skippedCount} icon={SkipForward} color={COLORS.warning} sub="No recipient resolved" />
          <StatCard label="Today" value={todayCount} icon={Mail} color={COLORS.accentDark} />
        </div>

        <div style={{ ...cardStyle, padding: 0, overflow: "hidden" }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 16px", borderBottom: `1px solid ${COLORS.border}`, flexWrap: "wrap", gap: 10 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 6, fontWeight: 700, fontSize: 14, color: COLORS.text }}>
              <Filter size={14} color={COLORS.textMuted} /> Entries <span style={{ color: COLORS.textMuted, fontWeight: 500 }}>({filtered.length})</span>
            </div>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8, border: `1px solid ${COLORS.border}`, borderRadius: 8, padding: "7px 11px", width: 190 }}>
                <Search size={14} color={COLORS.textMuted} />
                <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Recipient, subject, event" style={{ border: "none", outline: "none", fontSize: 13, width: "100%", fontFamily: "Inter, sans-serif" }} />
              </div>
              <select value={eventFilter} onChange={(e) => setEventFilter(e.target.value)} style={{ ...inputStyle, width: 180, padding: "7px 11px" }}>
                <option value="">All Events</option>
                {eventOptions.map((e) => <option key={e} value={e}>{e}</option>)}
              </select>
              <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} style={{ ...inputStyle, width: 140, padding: "7px 11px" }}>
                <option value="">All Statuses</option>
                <option value="Sent">Sent</option>
                <option value="Failed">Failed</option>
                <option value="Skipped">Skipped</option>
              </select>
              <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} style={{ ...inputStyle, width: 140, padding: "7px 11px" }} />
              <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} style={{ ...inputStyle, width: 140, padding: "7px 11px" }} />
            </div>
          </div>

          {listError && (
            <div style={{ padding: "12px 16px", color: COLORS.danger, fontSize: 13, display: "flex", alignItems: "center", gap: 8 }}>
              <AlertCircle size={14} /> {listError}
            </div>
          )}

          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr style={{ background: COLORS.bg }}>
                <th onClick={() => setSortDir(sortDir === "desc" ? "asc" : "desc")} style={{ textAlign: "left", padding: "10px 16px", fontSize: 12, color: COLORS.textMuted, fontWeight: 700, textTransform: "uppercase", letterSpacing: 0.3, cursor: "pointer", display: "flex", alignItems: "center", gap: 5 }}>
                  Sent <ArrowUpDown size={11} />
                </th>
                {["Event", "Recipient", "Subject", "Status"].map((h) => (
                  <th key={h} style={{ textAlign: "left", padding: "10px 16px", fontSize: 12, color: COLORS.textMuted, fontWeight: 700, textTransform: "uppercase", letterSpacing: 0.3 }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr><td colSpan={5} style={{ padding: 40, textAlign: "center", color: COLORS.textMuted }}>
                  <Loader2 size={18} className="spin" style={{ verticalAlign: "middle", marginRight: 8 }} /> Loading notification log…
                </td></tr>
              ) : filtered.length === 0 ? (
                <tr><td colSpan={5}><EmptyState icon={Bell} onRetry={refresh} /></td></tr>
              ) : filtered.map((r, i) => {
                const meta = statusMeta(r.deliveryStatus);
                const StatusIcon = meta.icon;
                return (
                  <tr key={r.guid} onClick={() => setDetail(r)} style={{ borderTop: `1px solid ${COLORS.border}`, background: i % 2 ? "COLORS.tableHead" : "#fff", cursor: "pointer" }}>
                    <td style={{ padding: "11px 16px", fontSize: 13, color: COLORS.textMuted, whiteSpace: "nowrap" }}>{r.sentDate ? new Date(r.sentDate).toLocaleString() : "—"}</td>
                    <td style={{ padding: "11px 16px", fontSize: 13.5, color: COLORS.text, fontWeight: 600 }}>{r.emailType}</td>
                    <td style={{ padding: "11px 16px", fontSize: 13.5, color: COLORS.text, maxWidth: 220, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{r.recipientEmail || "—"}</td>
                    <td style={{ padding: "11px 16px", fontSize: 13, color: COLORS.textMuted, maxWidth: 260, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{r.subjectLine || "—"}</td>
                    <td style={{ padding: "11px 16px" }}>
                      <span style={{ display: "inline-flex", alignItems: "center", gap: 5, fontSize: 12, fontWeight: 700, color: meta.color, background: meta.bg, borderRadius: 999, padding: "3px 10px" }}>
                        <StatusIcon size={12} /> {r.deliveryStatus || "—"}
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Slide-over detail panel — view only, matches the app's panel chrome
          without a form/save (nothing here is editable). */}
      {detail && (
        <>
          <div onClick={() => setDetail(null)} style={{ position: "fixed", inset: 0, background: "rgba(15,23,48,0.35)", zIndex: 40 }} />
          <div style={{ position: "fixed", top: 0, right: 0, bottom: 0, width: 420, maxWidth: "92vw", background: "#fff", boxShadow: "-18px 0 40px rgba(15,23,48,0.14)", zIndex: 41, display: "flex", flexDirection: "column" }}>
            <div style={{ padding: "18px 20px", borderBottom: `1px solid ${COLORS.border}`, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <div>
                <div style={{ fontFamily: "Sora, sans-serif", fontSize: 16, fontWeight: 700, color: COLORS.text }}>{detail.emailType}</div>
                <div style={{ fontSize: 12.5, color: COLORS.textMuted }}>{detail.sentDate ? new Date(detail.sentDate).toLocaleString() : "—"}</div>
              </div>
              <button onClick={() => setDetail(null)} style={{ border: "none", background: "transparent", cursor: "pointer", color: COLORS.textMuted }}><X size={18} /></button>
            </div>
            <div style={{ padding: 20, overflowY: "auto", display: "flex", flexDirection: "column", gap: 14 }}>
              {(() => {
                const meta = statusMeta(detail.deliveryStatus);
                const StatusIcon = meta.icon;
                return (
                  <span style={{ alignSelf: "flex-start", display: "inline-flex", alignItems: "center", gap: 6, fontSize: 12.5, fontWeight: 700, color: meta.color, background: meta.bg, borderRadius: 999, padding: "5px 12px" }}>
                    <StatusIcon size={13} /> {detail.deliveryStatus || "—"}
                  </span>
                );
              })()}
              {[
                ["To", detail.recipientEmail || "—"],
                ["Cc", detail.ccEmail || "—"],
                ["Subject", detail.subjectLine || "—"],
                ["Sent By", detail.sentBy || "—"],
              ].map(([label, value]) => (
                <div key={label}>
                  <div style={{ fontSize: 11.5, color: COLORS.textMuted, fontWeight: 700, textTransform: "uppercase", letterSpacing: 0.3, marginBottom: 3 }}>{label}</div>
                  <div style={{ fontSize: 13.5, color: COLORS.text, wordBreak: "break-word" }}>{value}</div>
                </div>
              ))}
              {detail.errorMessage && (
                <div>
                  <div style={{ fontSize: 11.5, color: COLORS.danger, fontWeight: 700, textTransform: "uppercase", letterSpacing: 0.3, marginBottom: 3 }}>Error</div>
                  <div style={{ fontSize: 13, color: COLORS.danger, background: COLORS.dangerSoft, borderRadius: 8, padding: "10px 12px" }}>{detail.errorMessage}</div>
                </div>
              )}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
